### ISSUE TITLE
Year display not showing well

### ISSUE THREAD

**Issue by btfloyd** [alecgorge/iguana-ios#17]
For some reason, the year isn't displayed correctly anymore.  It shows "19...."

I have to guess and guess to find the years I'm wanting.  

iPhone 5
iOS 9.0.2

**Comment by gglauberman** [comment]
Same for me

Gary Glauberman
9132002485

**Comment by jefreywith1f** [comment]
Same issue. IOS 9.1

**Comment by tase2** [comment]
Can there be anything done to fix this?

**Comment by alecgorge** [comment]
I submitted an update to the app store 9 days ago so it should be available very soon! Sorry for the issue.

**Comment by jefreywith1f** [comment]
Right on!  Thanks Alec - your app is fantastic!  Being able to favorite
songs and shows like you can in the Phish app would be so fantastic! Maybe
in pipeline for a future release??

**Comment by alecgorge** [comment]
@jefreywith1f yep that's in the next version as well. It just went into review right now so it might be available as soon as a couple hours from now!

**Comment by btfloyd** [comment]
Yeah!  Thank you.
