### ISSUE TITLE
App doesn't work in iPhone 4S

### ISSUE THREAD

**Issue by Dosran** [alecgorge/iguana-ios#2]
How come the app doesn't work on my iphone 4S? I go to play any of the shows and no sound comes out I get nothing?

**Comment by alecgorge** [comment]
It works fine for me on my 4S and I have never heard of any one else having this problem.

**Comment by Dosran** [comment]
So you just click on the show and it plays? Or is there a setting that's off on my phone? I can't figure it out, I click on a show and I've tried several of the links and nothing comes out of the headphones. 
Do I have to login or create an account or something?

**Comment by alecgorge** [comment]
As soon as a select a song it starts playing.

Make sure you select a source after you select a show

Sent from my iPhone

On Aug 3, 2014, at 4:27 PM, Dosran notifications@github.com wrote:

So you just click on the show and it plays? Or is there a setting that's
off on my phone? I can't figure it out, I click on a show and I've tried
several of the links and nothing comes out of the headphones.
Do I have to login or create an account or something?

**Comment by Dosran** [comment]
Yep I've been trying several different sources and shows, it sounds like a great app , maybe I should delete and reinstall the app?

**Comment by Dosran** [comment]
I get it it's one song at a time, awesome
Thanks

**Comment by Dosran** [comment]
Hi Alec
Is there a way to play multiple songs without having to click each song? This would be better while driving 
Thanks,

**Comment by alecgorge** [comment]
If you press one song, the next ones will play automatically when that one finishes.

**Comment by Dosran** [comment]
Sweet you've thought of everything
